/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ControladorRouteImport } from './routes/controlador'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as AuxiliarRouteImport } from './routes/auxiliar'
import { Route as AdministradorRouteImport } from './routes/administrador'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladorRoute = ControladorRouteImport.update({
  id: '/controlador',
  path: '/controlador',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuxiliarRoute = AuxiliarRouteImport.update({
  id: '/auxiliar',
  path: '/auxiliar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministradorRoute = AdministradorRouteImport.update({
  id: '/administrador',
  path: '/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/auxiliar': typeof AuxiliarRoute
  '/conductor': typeof ConductorRoute
  '/controlador': typeof ControladorRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/auxiliar': typeof AuxiliarRoute
  '/conductor': typeof ConductorRoute
  '/controlador': typeof ControladorRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/auxiliar': typeof AuxiliarRoute
  '/conductor': typeof ConductorRoute
  '/controlador': typeof ControladorRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrador'
    | '/auxiliar'
    | '/conductor'
    | '/controlador'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrador'
    | '/auxiliar'
    | '/conductor'
    | '/controlador'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/administrador'
    | '/auxiliar'
    | '/conductor'
    | '/controlador'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministradorRoute: typeof AdministradorRoute
  AuxiliarRoute: typeof AuxiliarRoute
  ConductorRoute: typeof ConductorRoute
  ControladorRoute: typeof ControladorRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlador': {
      id: '/controlador'
      path: '/controlador'
      fullPath: '/controlador'
      preLoaderRoute: typeof ControladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auxiliar': {
      id: '/auxiliar'
      path: '/auxiliar'
      fullPath: '/auxiliar'
      preLoaderRoute: typeof AuxiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrador': {
      id: '/administrador'
      path: '/administrador'
      fullPath: '/administrador'
      preLoaderRoute: typeof AdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministradorRoute: AdministradorRoute,
  AuxiliarRoute: AuxiliarRoute,
  ConductorRoute: ConductorRoute,
  ControladorRoute: ControladorRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
