/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as SeatsRouteImport } from './routes/seats'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PassengersRouteImport } from './routes/passengers'
import { Route as MisViajesRouteImport } from './routes/mis-viajes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ControladorRouteImport } from './routes/controlador'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as AuxiliarRouteImport } from './routes/auxiliar'
import { Route as AdministradorRouteImport } from './routes/administrador'
import { Route as IndexRouteImport } from './routes/index'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsRoute = SeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengersRoute = PassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => rootRouteImport,
} as any)
const MisViajesRoute = MisViajesRouteImport.update({
  id: '/mis-viajes',
  path: '/mis-viajes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladorRoute = ControladorRouteImport.update({
  id: '/controlador',
  path: '/controlador',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuxiliarRoute = AuxiliarRouteImport.update({
  id: '/auxiliar',
  path: '/auxiliar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministradorRoute = AdministradorRouteImport.update({
  id: '/administrador',
  path: '/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/auxiliar': typeof AuxiliarRoute
  '/conductor': typeof ConductorRoute
  '/controlador': typeof ControladorRoute
  '/login': typeof LoginRoute
  '/mis-viajes': typeof MisViajesRoute
  '/passengers': typeof PassengersRoute
  '/payment': typeof PaymentRoute
  '/seats': typeof SeatsRoute
  '/ticket': typeof TicketRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/auxiliar': typeof AuxiliarRoute
  '/conductor': typeof ConductorRoute
  '/controlador': typeof ControladorRoute
  '/login': typeof LoginRoute
  '/mis-viajes': typeof MisViajesRoute
  '/passengers': typeof PassengersRoute
  '/payment': typeof PaymentRoute
  '/seats': typeof SeatsRoute
  '/ticket': typeof TicketRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/auxiliar': typeof AuxiliarRoute
  '/conductor': typeof ConductorRoute
  '/controlador': typeof ControladorRoute
  '/login': typeof LoginRoute
  '/mis-viajes': typeof MisViajesRoute
  '/passengers': typeof PassengersRoute
  '/payment': typeof PaymentRoute
  '/seats': typeof SeatsRoute
  '/ticket': typeof TicketRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrador'
    | '/auxiliar'
    | '/conductor'
    | '/controlador'
    | '/login'
    | '/mis-viajes'
    | '/passengers'
    | '/payment'
    | '/seats'
    | '/ticket'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrador'
    | '/auxiliar'
    | '/conductor'
    | '/controlador'
    | '/login'
    | '/mis-viajes'
    | '/passengers'
    | '/payment'
    | '/seats'
    | '/ticket'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/administrador'
    | '/auxiliar'
    | '/conductor'
    | '/controlador'
    | '/login'
    | '/mis-viajes'
    | '/passengers'
    | '/payment'
    | '/seats'
    | '/ticket'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministradorRoute: typeof AdministradorRoute
  AuxiliarRoute: typeof AuxiliarRoute
  ConductorRoute: typeof ConductorRoute
  ControladorRoute: typeof ControladorRoute
  LoginRoute: typeof LoginRoute
  MisViajesRoute: typeof MisViajesRoute
  PassengersRoute: typeof PassengersRoute
  PaymentRoute: typeof PaymentRoute
  SeatsRoute: typeof SeatsRoute
  TicketRoute: typeof TicketRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats': {
      id: '/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passengers': {
      id: '/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof PassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-viajes': {
      id: '/mis-viajes'
      path: '/mis-viajes'
      fullPath: '/mis-viajes'
      preLoaderRoute: typeof MisViajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlador': {
      id: '/controlador'
      path: '/controlador'
      fullPath: '/controlador'
      preLoaderRoute: typeof ControladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auxiliar': {
      id: '/auxiliar'
      path: '/auxiliar'
      fullPath: '/auxiliar'
      preLoaderRoute: typeof AuxiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrador': {
      id: '/administrador'
      path: '/administrador'
      fullPath: '/administrador'
      preLoaderRoute: typeof AdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministradorRoute: AdministradorRoute,
  AuxiliarRoute: AuxiliarRoute,
  ConductorRoute: ConductorRoute,
  ControladorRoute: ControladorRoute,
  LoginRoute: LoginRoute,
  MisViajesRoute: MisViajesRoute,
  PassengersRoute: PassengersRoute,
  PaymentRoute: PaymentRoute,
  SeatsRoute: SeatsRoute,
  TicketRoute: TicketRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
